# 1. Linear Regression Implementation from Scratch

In [1]:
import torch
import random

## 1.1 Generating the dataset

The true parameters generating our dataset will be $w=[2,−3.4]^{T}$ and $b=4.2$, and our synthetic labels will be assigned according to the following linear model with the noise term ϵ.

In [2]:
def synthetic_data(w, b, num_examples):
    # Random X
    X = torch.normal(0, 1, (num_examples, len(w)))
    # Calculate Y
    y = torch.matmul(X, w) + b
    # Add noise
    y += torch.normal(0, 0.01, y.shape)
    return X, y.reshape((-1, 1))

true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = synthetic_data(true_w, true_b, 1000)

print(f'Example\nFeatures: {features[0]}\nLabel: {labels[0]}')

Example
Features: tensor([0.9791, 1.5140])
Label: tensor([1.0220])


## 1.2 Reading the dataset

In [3]:
def data_iter(batch_size, features, labels):
    n = len(features)
    indices = list(range(n))
    random.shuffle(indices)
    for i in range(0, n, batch_size):
        batch_indices = torch.tensor(
            indices[i: min(i + batch_size, n)])
        yield features[batch_indices], labels[batch_indices]

In [4]:
batch_size = 10

for X, y in data_iter(batch_size, features, labels):
    print('Features:\n', X, '\nLabels\n', y)
    break

Features:
 tensor([[ 0.3268, -0.7618],
        [ 0.5584, -1.3536],
        [-0.0169,  2.3528],
        [-0.6741,  0.6355],
        [ 1.2003, -0.5752],
        [ 0.7428, -1.6536],
        [-1.8204, -0.5661],
        [-0.6830, -1.2578],
        [-1.1388, -0.3953],
        [-0.1335,  0.3235]]) 
Labels
 tensor([[ 7.4550],
        [ 9.9077],
        [-3.8294],
        [ 0.6859],
        [ 8.5578],
        [11.3089],
        [ 2.4886],
        [ 7.1105],
        [ 3.2582],
        [ 2.8335]])


## 1.3 Initializing model parameters

In [5]:
w = torch.normal(0, 0.01, size=(2,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

## 1.4 Defining the model

In [6]:
def linreg(X, w, b):
    return torch.matmul(X, w) + b

## 1.5 Defining the Loss Function

In [7]:
def squared_loss(y_hat, y):
    return (y_hat - y.reshape(y_hat.shape))**2 / 2

## 1.6 Defining the Optimization Algorithm 

Because our loss is calculated as a sum over the minibatch of examples, we normalize our step size by the batch size (batch_size), so that the magnitude of a typical step size does not depend heavily on our choice of the batch size.

    torch.no_grad(): context manager that disabled gradient calculation (temporarily sets all of the requires_grad flags to False)
    
    torch.Tensor.grad: This attribute is None by default and becomes a Tensor the first time a call to backward() computes gradients for self. The attribute will then contain the gradients computed and future calls to backward() will accumulate (add) gradients into it.

In [8]:
def sgd(params, lr, batch_size):
    with torch.no_grad():
        for param in params:
            param -= lr * param.grad / batch_size
            param.grad.zero_()

## 1.7 Training

In [9]:
lr = 0.03
epochs = 3

for epoch in range(epochs):
    for X, y in data_iter(batch_size, features, labels):
        l = squared_loss(linreg(X, w, b), y)
        l.sum().backward()
        sgd([w, b], lr, batch_size)
    with torch.no_grad():
        train_l = squared_loss(linreg(features, w, b), labels)
        print(f'epoch {epoch + 1}, loss {float(train_l.mean()):f}')

epoch 1, loss 0.031972
epoch 2, loss 0.000108
epoch 3, loss 0.000048


# 2. Concise implementation of Linear regression

In [10]:
import numpy as np
from torch.utils import data
from torch import nn

## 2.1 Reading the dataset

* **torch.utils.data.DataLoader:** Data loader. Combines a dataset and a sampler, and provides an iterable over the given dataset.

* **torch.utils.data.Dataset:** An abstract class representing a Dataset.

In [11]:
def load_array(data_arrays, batch_size, is_train=True):
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [12]:
next(iter(data_iter))

[tensor([[-0.6234, -0.0224],
         [ 0.4901,  0.4181],
         [ 1.0842, -0.2557],
         [ 0.1818,  0.1437],
         [-0.6741,  0.6355],
         [-2.8698,  1.3331],
         [-0.0230, -0.8326],
         [-1.3872, -0.9467],
         [-0.0036, -0.6795],
         [ 1.8438, -0.7314]]), tensor([[ 3.0278],
         [ 3.7481],
         [ 7.2583],
         [ 4.0649],
         [ 0.6859],
         [-6.0841],
         [ 6.9711],
         [ 4.6306],
         [ 6.4995],
         [10.3686]])]

## 2.2 Defining the Model

* **torch.nn.Sequential(*args):** A sequential container. Modules will be added to it in the order they are passed in the constructor. Alternatively, an ordered dict of modules can also be passed in.

* **torch.nn.Linear(in_features, out_features, bias=True):** Applies a linear transformation to the incoming data: $y=xW+b$

In [23]:
lr = nn.Sequential(nn.Linear(2, 1))

## 2.3 Initializing Model Parameters

In [24]:
lr[0].weight.data.normal_(0, 0.01)

tensor([[ 0.0233, -0.0059]])

In [25]:
lr[0].bias.data.fill_(0)

tensor([0.])

## 2.4 Defining the Loss Function

In [26]:
loss = nn.MSELoss()

## 2.5 Defining the Optimization Algorithm

In [27]:
trainer = torch.optim.SGD(lr.parameters(), lr=0.03)

## 2.6 Training

* **step(closure):** Performs a single optimization step (parameter update).

* **zero_grad():** Sets the gradients of all optimized torch.Tensor s to zero.

In [28]:
epochs = 3
for epoch in range(epochs):
    for X, y in data_iter:
        l = loss(lr(X) ,y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(lr(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000201
epoch 2, loss 0.000097
epoch 3, loss 0.000097
